# Generated by Django 4.0.4 on 2022-04-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sazonunivalle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tiempo_preparacion',
            field=models.DurationField(max_length=10),
        ),
    ]
