# Generated by Django 4.0.4 on 2022-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sazonunivalle', '0002_alter_plato_tiempo_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
