# Generated by Django 4.0.4 on 2022-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sazonunivalle', '0004_alter_plato_tiempo_preparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tiempo_preparacion',
            field=models.DurationField(),
        ),
    ]
