# Generated by Django 4.0.4 on 2022-04-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sazonunivalle', '0005_alter_plato_tiempo_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='alimento',
            field=models.ManyToManyField(to='sazonunivalle.alimento'),
        ),
    ]
